const PDFDocument = require("pdfkit");
const pool = require("../../config/db");

const getReceiptPayment = async (paymentId, user) => {
  let accessClause;

  if (user.role === "owner") {
    accessClause = "properties.owner_id = $2";
  } else if (user.role === "tenant") {
    accessClause = "tenancies.tenant_id = $2";
  } else {
    return null;
  }

  const result = await pool.query(
    `
    SELECT
      payments.id AS payment_id,
      payments.amount,
      payments.payment_method,
      payments.payment_date,
      payments.transaction_id,
      payments.status AS payment_status,
      rent_schedules.month,
      rent_schedules.year,
      rent_schedules.amount AS rent_amount,
      tenant.name AS tenant_name,
      tenant.email AS tenant_email,
      owners.name AS owner_name,
      properties.name AS property_name,
      units.name AS unit_name
    FROM payments
    INNER JOIN rent_schedules ON rent_schedules.id = payments.rent_schedule_id
    INNER JOIN tenancies ON tenancies.id = rent_schedules.tenancy_id
    INNER JOIN users AS tenant ON tenant.id = tenancies.tenant_id
    INNER JOIN units ON units.id = tenancies.unit_id
    INNER JOIN properties ON properties.id = units.property_id
    INNER JOIN users AS owners ON owners.id = properties.owner_id
    WHERE payments.id = $1
      AND ${accessClause}
    `,
    [paymentId, user.id]
  );

  return result.rows[0];
};

const formatMoney = (amount) =>
  `INR ${Number(amount || 0).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

const formatDate = (date) => {
  if (!date) return "N/A";

  return new Intl.DateTimeFormat("en-IN", {
    timeZone: "Asia/Kolkata",
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  }).format(new Date(date));
};

const generateReceipt = (paymentData, res) => {
  const doc = new PDFDocument({ margin: 50 });
  const filename = `receipt-${paymentData.payment_id}.pdf`;

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);

  doc.pipe(res);

  doc.fontSize(20).text("Rent Receipt", { align: "center" });
  doc.moveDown();
  doc.fontSize(11).text(`Receipt ID: ${paymentData.payment_id}`);
  doc.text(`Transaction ID: ${paymentData.transaction_id || "N/A"}`);
  doc.text(`Payment Date: ${formatDate(paymentData.payment_date)}`);

  doc.moveDown();
  doc.fontSize(14).text("Tenant");
  doc.fontSize(11).text(`Name: ${paymentData.tenant_name}`);
  doc.text(`Email: ${paymentData.tenant_email}`);

  doc.moveDown();
  doc.fontSize(14).text("Rent Details");
  doc.fontSize(11).text(`Property: ${paymentData.property_name}`);
  doc.text(`Unit: ${paymentData.unit_name}`);
  doc.text(`Rent Period: ${paymentData.month}/${paymentData.year}`);
  doc.text(`Rent Amount: ${formatMoney(paymentData.rent_amount)}`);

  doc.moveDown();
  doc.fontSize(14).text("Payment");
  doc.fontSize(11).text(`Amount Paid: ${formatMoney(paymentData.amount)}`);
  doc.text(`Payment Method: ${paymentData.payment_method || "N/A"}`);
  doc.text(`Status: ${paymentData.payment_status || "success"}`);

  doc.moveDown(2);
  doc.fontSize(10).text("This receipt was generated by Rent Management System.", {
    align: "center",
  });

  doc.end();
};

module.exports = { getReceiptPayment, generateReceipt };
